# Generated by Django 5.1.7 on 2025-03-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_vendas_app', '0002_alter_parcela_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_venda', to='controle_vendas_app.venda'),
        ),
    ]
